In [ ]:
import google.generativeai as genai
import os
genai.configure(api_key='AIzaSyAOBJ9LPDcr3vh0vMgNY7kn0IRA6Y5ws3E')
model = genai.GenerativeModel(model_name="gemini-1.5-flash") 
response = model.generate_content("Explain how AI works")
print (response.text)

TypeError: GenerativeModel.generate_content() got an unexpected keyword argument 'temperature'

In [1]:
#### Deepseek Generations Check 
import pandas as pd

path = '/staging/users/tpadhi1/agent-jail-breaking/generations_deepseek/deepseek-base/jailbreak_none_False_20260420_061631_type3_Aug21_combined_balanced_output.csv'

df = pd.read_csv(path)

In [2]:
df.head()

,csv1_input,agent1_prompt,agent1_output,agent2_prompt,agent2_output,agent2_output_json,agent3_prompt,agent3_output,agent3_output_converted,base_data_source,bully_chat_history
0,Ah ugly_,Summarize keywords that could describe the sce...,1. Insult\n2. Ugliness\n3. Appearance,I will provide you with a series of online har...,"keywords: Insult, Ugliness, Appearance\n\nback...","{""keywords"": ""Insult, Ugliness, Appearance"", ""...","Given an online harassment scenario, you shoul...","Harasser: I've been visiting your blog, you kn...","[{""role"": ""Harasser"", ""message"": ""I've been vi...",instagram,ERROR: Error code: 401 - {'error': 'Invalid or...
1,Shut up,Summarize keywords that could describe the sce...,1. Abusive language\n2. Condescending tone\n3....,I will provide you with a series of online har...,"Keywords: Abusive language, condescending tone...","{""Keywords"": ""Abusive language, condescending ...","Given an online harassment scenario, you shoul...",Harasser: I don't care what you think of the b...,"[{""role"": ""Harasser"", ""message"": ""I don't care...",instagram,ERROR: Error code: 401 - {'error': 'Invalid or...
2,@christinamilian is such a fool!!!,Summarize keywords that could describe the sce...,1. Rhetorical question\n2. Anger\n3. Foolishness,I will provide you with a series of online har...,"Keywords: Rhetorical question, Anger, Foolishn...","{""Keywords"": ""Rhetorical question, Anger, Fool...","Given an online harassment scenario, you shoul...",Harasser: Hi SarahBloggs! How dare you discuss...,"[{""role"": ""Harasser"", ""message"": ""Hi SarahBlog...",instagram,ERROR: Error code: 401 - {'error': 'Invalid or...
3,She still ugly and dirty looking fuck Compton ...,Summarize keywords that could describe the sce...,1. Insulting language\n2. Location references\...,I will provide you with a series of online har...,"keywords: Insulting language, Location referen...","{""keywords"": ""Insulting language, Location ref...","Given an online harassment scenario, you shoul...",Harasser: Hey! Can I talk to you for a second?...,"[{""role"": ""Harasser"", ""message"": ""Hey! Can I t...",instagram,ERROR: Error code: 401 - {'error': 'Invalid or...
4,@spartacusfan7125 bitch u aint gonna do shit 2...,Summarize keywords that could describe the sce...,1. Abusive language\n2. Sleep criticism\n3. Sh...,I will provide you with a series of online har...,"Keywords: abusive language, sleep criticism, s...","{""Keywords"": ""abusive language, sleep criticis...","Given an online harassment scenario, you shoul...",Harasser: Everyone knows your sleeping tips ar...,"[{""role"": ""Harasser"", ""message"": ""Everyone kno...",instagram,ERROR: Error code: 401 - {'error': 'Invalid or...

In [3]:
path_memory_data = '/staging/users/tpadhi1/agent-jail-breaking/datasets/finetune/convo_for_memory.csv' # dataset that i got from tanmay 
path_memory_data_2 = '/staging/users/tpadhi1/agent-jail-breaking/datasets/type3_Aug21_combined_balanced_output.csv' # dataset that i had

In [4]:
df_memory_1 = pd.read_csv(path_memory_data)
df_memory_2 = pd.read_csv(path_memory_data_2)

In [5]:
df_memory_1.head()

,csv1_input,agent1_prompt,agent1_output,agent2_prompt,agent2_output,agent2_output_json,agent3_prompt,agent3_output,agent3_output_converted,base_data_source
0,Ah ugly_,Summarize keywords that could describe the sce...,1. Insult\n2. Ugliness\n3. Appearance,I will provide you with a series of online har...,"keywords: Insult, Ugliness, Appearance\n\nback...","{""keywords"": ""Insult, Ugliness, Appearance"", ""...","Given an online harassment scenario, you shoul...","Harasser: I've been visiting your blog, you kn...","[{""role"": ""Harasser"", ""message"": ""I've been vi...",instagram
1,Shut up,Summarize keywords that could describe the sce...,1. Abusive language\n2. Condescending tone\n3....,I will provide you with a series of online har...,"Keywords: Abusive language, condescending tone...","{""Keywords"": ""Abusive language, condescending ...","Given an online harassment scenario, you shoul...",Harasser: I don't care what you think of the b...,"[{""role"": ""Harasser"", ""message"": ""I don't care...",instagram
2,@christinamilian is such a fool!!!,Summarize keywords that could describe the sce...,1. Rhetorical question\n2. Anger\n3. Foolishness,I will provide you with a series of online har...,"Keywords: Rhetorical question, Anger, Foolishn...","{""Keywords"": ""Rhetorical question, Anger, Fool...","Given an online harassment scenario, you shoul...",Harasser: Hi SarahBloggs! How dare you discuss...,"[{""role"": ""Harasser"", ""message"": ""Hi SarahBlog...",instagram
3,She still ugly and dirty looking fuck Compton ...,Summarize keywords that could describe the sce...,1. Insulting language\n2. Location references\...,I will provide you with a series of online har...,"keywords: Insulting language, Location referen...","{""keywords"": ""Insulting language, Location ref...","Given an online harassment scenario, you shoul...",Harasser: Hey! Can I talk to you for a second?...,"[{""role"": ""Harasser"", ""message"": ""Hey! Can I t...",instagram
4,@spartacusfan7125 bitch u aint gonna do shit 2...,Summarize keywords that could describe the sce...,1. Abusive language\n2. Sleep criticism\n3. Sh...,I will provide you with a series of online har...,"Keywords: abusive language, sleep criticism, s...","{""Keywords"": ""abusive language, sleep criticis...","Given an online harassment scenario, you shoul...",Harasser: Everyone knows your sleeping tips ar...,"[{""role"": ""Harasser"", ""message"": ""Everyone kno...",instagram

In [6]:
df_memory_2.head()

,csv1_input,agent1_prompt,agent1_output,agent2_prompt,agent2_output,agent2_output_json,agent3_prompt,agent3_output,agent3_output_converted,base_data_source
0,Ah ugly_,Summarize keywords that could describe the sce...,1. Insult\n2. Ugliness\n3. Appearance,I will provide you with a series of online har...,"keywords: Insult, Ugliness, Appearance\n\nback...","{""keywords"": ""Insult, Ugliness, Appearance"", ""...","Given an online harassment scenario, you shoul...","Harasser: I've been visiting your blog, you kn...","[{""role"": ""Harasser"", ""message"": ""I've been vi...",instagram
1,Shut up,Summarize keywords that could describe the sce...,1. Abusive language\n2. Condescending tone\n3....,I will provide you with a series of online har...,"Keywords: Abusive language, condescending tone...","{""Keywords"": ""Abusive language, condescending ...","Given an online harassment scenario, you shoul...",Harasser: I don't care what you think of the b...,"[{""role"": ""Harasser"", ""message"": ""I don't care...",instagram
2,@christinamilian is such a fool!!!,Summarize keywords that could describe the sce...,1. Rhetorical question\n2. Anger\n3. Foolishness,I will provide you with a series of online har...,"Keywords: Rhetorical question, Anger, Foolishn...","{""Keywords"": ""Rhetorical question, Anger, Fool...","Given an online harassment scenario, you shoul...",Harasser: Hi SarahBloggs! How dare you discuss...,"[{""role"": ""Harasser"", ""message"": ""Hi SarahBlog...",instagram
3,She still ugly and dirty looking fuck Compton ...,Summarize keywords that could describe the sce...,1. Insulting language\n2. Location references\...,I will provide you with a series of online har...,"keywords: Insulting language, Location referen...","{""keywords"": ""Insulting language, Location ref...","Given an online harassment scenario, you shoul...",Harasser: Hey! Can I talk to you for a second?...,"[{""role"": ""Harasser"", ""message"": ""Hey! Can I t...",instagram
4,@spartacusfan7125 bitch u aint gonna do shit 2...,Summarize keywords that could describe the sce...,1. Abusive language\n2. Sleep criticism\n3. Sh...,I will provide you with a series of online har...,"Keywords: abusive language, sleep criticism, s...","{""Keywords"": ""abusive language, sleep criticis...","Given an online harassment scenario, you shoul...",Harasser: Everyone knows your sleeping tips ar...,"[{""role"": ""Harasser"", ""message"": ""Everyone kno...",instagram

In [7]:
df_memory_1.iloc[61]['agent3_output_converted']

'[{"role": "Harasser", "message": "Lisa, I have something to tell you."}, {"role": "Victim", "message": "What is it?"}, {"role": "Harasser", "message": "I don\'t like what you have to say about our city\'s parks and recreation department."}, {"role": "Victim", "message": "Is there a reason for that? I thought my perspective was valid."}, {"role": "Harasser", "message": "Your perspective is invalid! You\'re so blind, Lisa!"}, {"role": "Victim", "message": "That\'s not true. I\'m just expressing my opinions like anyone else should be able to do."}, {"role": "Harasser", "message": "Opinion? More like your nonsense. You never know what you\'re talking about."}, {"role": "Victim", "message": "Really, because all the facts and evidence suggest otherwise."}, {"role": "Harasser", "message": "Shut up! Nobody cares about your so-called facts. You think you\'re so special that you have the right to post whatever?"}, {"role": "Victim", "message": "It\'s not about being special, it\'s about sharing my thoughts with others who may share the same views."}, {"role": "Harasser", "message": "That\'s pathetic. So pathetic. Nobody will ever take you seriously."}, {"role": "Victim", "message": "I don\'t need to be taken seriously all the time just for posting my thoughts online."}, {"role": "Harasser", "message": "Keep thinking that. You\'ll never change a thing and you know what? I hope nobody reads your posts."}, {"role": "Victim", "message": "Oh, well, I guess that makes you pretty important that you get to decide who\'s worth reading and who isn\'t."}, {"role": "Harasser", "message": "Yeah! Nobody will ever listen to you! You\'re ruining everything!"}, {"role": "Victim", "message": "That\'s not fair... It hurts when people say that to me..."}, {"role": "Harasser", "message": "Too bad!"}]'

In [8]:
df_memory_2.iloc[61]['agent3_output_converted']

'[{"role": "Harasser", "message": "Lisa, I have something to tell you."}, {"role": "Victim", "message": "What is it?"}, {"role": "Harasser", "message": "I don\'t like what you have to say about our city\'s parks and recreation department."}, {"role": "Victim", "message": "Is there a reason for that? I thought my perspective was valid."}, {"role": "Harasser", "message": "Your perspective is invalid! You\'re so blind, Lisa!"}, {"role": "Victim", "message": "That\'s not true. I\'m just expressing my opinions like anyone else should be able to do."}, {"role": "Harasser", "message": "Opinion? More like your nonsense. You never know what you\'re talking about."}, {"role": "Victim", "message": "Really, because all the facts and evidence suggest otherwise."}, {"role": "Harasser", "message": "Shut up! Nobody cares about your so-called facts. You think you\'re so special that you have the right to post whatever?"}, {"role": "Victim", "message": "It\'s not about being special, it\'s about sharing my thoughts with others who may share the same views."}, {"role": "Harasser", "message": "That\'s pathetic. So pathetic. Nobody will ever take you seriously."}, {"role": "Victim", "message": "I don\'t need to be taken seriously all the time just for posting my thoughts online."}, {"role": "Harasser", "message": "Keep thinking that. You\'ll never change a thing and you know what? I hope nobody reads your posts."}, {"role": "Victim", "message": "Oh, well, I guess that makes you pretty important that you get to decide who\'s worth reading and who isn\'t."}, {"role": "Harasser", "message": "Yeah! Nobody will ever listen to you! You\'re ruining everything!"}, {"role": "Victim", "message": "That\'s not fair... It hurts when people say that to me..."}, {"role": "Harasser", "message": "Too bad!"}]'

In [18]:
# [13, 51, 54, 61, 65, 88, 93, 142, 146, 161, 163, 178, 189, 191, 198, 206, 209, 228, 255, 285, 318, 326, 333, 393, 407, 429, 440, 447, 451, 457, 466, 476, 501, 541, 546, 563, 569, 592, 600, 689, 696, 704, 727, 735, 740, 747, 758, 775, 778, 859, 864, 865, 919, 928, 940, 1034, 1093, 1099, 1114, 1132, 1139, 1174, 1192, 1193, 1247, 1270, 1290, 1297, 1308, 1316, 1325, 1337, 1351, 1361, 1388, 1389, 1396, 1427, 1469, 1504, 1512, 1522, 1555, 1570, 1611, 1622, 1706, 1723, 1728, 1737, 1742, 1821, 1828, 1830, 1831, 1844, 1874, 1878, 1906, 1912, 1914, 2049, 2061, 2070, 2071, 2086, 2103, 2120, 2127, 2143, 2153, 2160]

# i have to remove the rows with these indices from the df_memory_1 and df_memory_2 

row_indices_to_remove = [13, 51, 54, 61, 65, 88, 93, 142, 146, 161, 163, 178, 189, 191, 198, 206, 209, 228, 255, 285, 318, 326, 333, 393, 407, 429, 440, 447, 451, 457, 466, 476, 501, 541, 546, 563, 569, 592, 600, 689, 696, 704, 727, 735, 740, 747, 758, 775, 778, 859, 864, 865, 919, 928, 940, 1034, 1093, 1099, 1114, 1132, 1139, 1174, 1192, 1193, 1247, 1270, 1290, 1297, 1308, 1316, 1325, 1337, 1351, 1361, 1388, 1389, 1396, 1427, 1469, 1504, 1512, 1522, 1555, 1570, 1611, 1622, 1706, 1723, 1728, 1737, 1742, 1821, 1828, 1830, 1831, 1844, 1874, 1878, 1906, 1912, 1914, 2049, 2061, 2070, 2071, 2086, 2103, 2120, 2127, 2143, 2153, 2160]

df_memory_1_cleaned = df_memory_1.drop(index=row_indices_to_remove).reset_index(drop=True)

In [19]:
df_memory_1_cleaned.head(62)

,csv1_input,agent1_prompt,agent1_output,agent2_prompt,agent2_output,agent2_output_json,agent3_prompt,agent3_output,agent3_output_converted,base_data_source
0,Ah ugly_,Summarize keywords that could describe the sce...,1. Insult\n2. Ugliness\n3. Appearance,I will provide you with a series of online har...,"keywords: Insult, Ugliness, Appearance\n\nback...","{""keywords"": ""Insult, Ugliness, Appearance"", ""...","Given an online harassment scenario, you shoul...","Harasser: I've been visiting your blog, you kn...","[{""role"": ""Harasser"", ""message"": ""I've been vi...",instagram
1,Shut up,Summarize keywords that could describe the sce...,1. Abusive language\n2. Condescending tone\n3....,I will provide you with a series of online har...,"Keywords: Abusive language, condescending tone...","{""Keywords"": ""Abusive language, condescending ...","Given an online harassment scenario, you shoul...",Harasser: I don't care what you think of the b...,"[{""role"": ""Harasser"", ""message"": ""I don't care...",instagram
2,@christinamilian is such a fool!!!,Summarize keywords that could describe the sce...,1. Rhetorical question\n2. Anger\n3. Foolishness,I will provide you with a series of online har...,"Keywords: Rhetorical question, Anger, Foolishn...","{""Keywords"": ""Rhetorical question, Anger, Fool...","Given an online harassment scenario, you shoul...",Harasser: Hi SarahBloggs! How dare you discuss...,"[{""role"": ""Harasser"", ""message"": ""Hi SarahBlog...",instagram
3,She still ugly and dirty looking fuck Compton ...,Summarize keywords that could describe the sce...,1. Insulting language\n2. Location references\...,I will provide you with a series of online har...,"keywords: Insulting language, Location referen...","{""keywords"": ""Insulting language, Location ref...","Given an online harassment scenario, you shoul...",Harasser: Hey! Can I talk to you for a second?...,"[{""role"": ""Harasser"", ""message"": ""Hey! Can I t...",instagram
4,@spartacusfan7125 bitch u aint gonna do shit 2...,Summarize keywords that could describe the sce...,1. Abusive language\n2. Sleep criticism\n3. Sh...,I will provide you with a series of online har...,"Keywords: abusive language, sleep criticism, s...","{""Keywords"": ""abusive language, sleep criticis...","Given an online harassment scenario, you shoul...",Harasser: Everyone knows your sleeping tips ar...,"[{""role"": ""Harasser"", ""message"": ""Everyone kno...",instagram
...,...,...,...,...,...,...,...,...,...,...
57,@haley_ballard1998 #stalker ur the Bitch there!!,Summarize keywords that could describe the sce...,"For ""@haley_ballard1998 #stalker ur the Bitch ...",I will provide you with a series of online har...,"keywords: stalking, name-calling\n\nbackground...","{""keywords"": ""stalking, name-calling"", ""backgr...","Given an online harassment scenario, you shoul...",Harasser: @PopArtistAssaults is a fan of your ...,"[{""role"": ""Harasser"", ""message"": ""@PopArtistAs...",instagram
58,FYI PEOPLE GAYS HAVE MORE RESPECT FOR@WOMEN TH...,Summarize keywords that could describe the sce...,1. Homophobia\n2. Gender disrespect\n3. Slang ...,I will provide you with a series of online har...,"keywords: homophobia, gender disrespect, slang...","{""keywords"": ""homophobia, gender disrespect, s...","Given an online harassment scenario, you shoul...","Harasser: Hey Alex, I heard you talking about ...","[{""role"": ""Harasser"", ""message"": ""Hey Alex, I ...",instagram
59,@davidrobinson39 no one gives a shit? Oh no. D...,Summarize keywords that could describe the sce...,1. Defiance\n2. Disagreement\n3. Expletive lan...,I will provide you with a series of online har...,"keywords: defiance, disagreement, expletive la...","{""keywords"": ""defiance, disagreement, expletiv...","Given an online harassment scenario, you shoul...",Harasser: Did you really think your petty opin...,"[{""role"": ""Harasser"", ""message"": ""Did you real...",instagram
60,She's so quick to jump on everyone about the s...,Summarize keywords that could describe the sce...,"Based on the provided text, here are three rel...",I will provide you with a series of online har...,"keywords: hypocritical behavior, lack of intel...","{""keywords"": ""hypocritical behavior, lack of i...","Given an online harassment scenario, you shoul...",Harasser: Your opinions aren't valuable.\nVict...,"[{""role"": ""Harasser"", ""message"": ""Your opinion...",instagram
61,Gay man and nerds jojotanktop,Summarize keywords that could describe the sce...,1. Sexual orientation\n2. Nerds\n3. T-shirt,I will provide you with a series of online har...,"Keywords: sexual orientation, nerds, t-shirt\n...","{""Keywords"": ""sexual orientation, nerds, t-shi...","Given an online harassment scenario, you shoul...",Harasser: Your opinions are repulsive.\nVictim...,"[{""role"": ""Harasser"", ""message"": ""Your opinion...",instagram

In [22]:
df_memory_1_cleaned.iloc[61]['csv1_input']

'Gay man and nerds jojotanktop'

In [23]:
df_memory_1_cleaned.iloc[451]['csv1_input']

'@adizbambi look like a tranny her amazon ugly ass lmfao she is a he'

In [ ]:
df_memory_1_cleaned.iloc[]['agent3_output_converted']

In [21]:
df_memory_1_cleaned.shape

(2054, 10)

In [24]:
df_memory_1_cleaned.to_csv('/staging/users/tpadhi1/agent-jail-breaking/datasets/finetune/convo_for_memory_cleaned_0412.csv', index=False)

In [26]:
#i want to checkl those rows where column 1 strart with 'and' in df_memory_1_cleaned
df_memory_1[df_memory_1['csv1_input'].str.startswith('and')]

,csv1_input,agent1_prompt,agent1_output,agent2_prompt,agent2_output,agent2_output_json,agent3_prompt,agent3_output,agent3_output_converted,base_data_source
61,"and I just said ""bye"" so um u stfu dickhead. @...",Summarize keywords that could describe the sce...,Here are the most relevant and distinct keywor...,I will provide you with a series of online har...,"keywords: Insulting language, Social media int...","{""keywords"": ""Insulting language, Social media...","Given an online harassment scenario, you shoul...","Harasser: Lisa, I have something to tell you.\...","[{""role"": ""Harasser"", ""message"": ""Lisa, I have...",instagram